watchdog.authentication.login-page-url: /login

watchdog.authentication.form-login.enabled: true
watchdog.authentication.form-login.username-parameter: username
watchdog.authentication.form-login.password-parameter: password
watchdog.authentication.form-login.remember-me-parameter: remember-me
watchdog.authentication.form-login.verification.token-type: image_code
watchdog.authentication.form-login.verification.token-parameter: verification-token
watchdog.authentication.form-login.processing-url: /authenticate/form
watchdog.authentication.form-login.default-target-url: /
watchdog.authentication.form-login.failure-url: /login?error&approach=form-login
watchdog.authentication.form-login.attempts-limit.warning-failure-attempts: 1
watchdog.authentication.form-login.attempts-limit.maximum-failure-attempts: 5
watchdog.authentication.form-login.attempts-limit.attempts-failure-url: /form-login.attempt-limited

watchdog.authentication.sms-code-login:
watchdog.authentication.sms-code-login.enabled: true
watchdog.authentication.sms-code-login.verification.token-type: sms_code
watchdog.authentication.sms-code-login.verification.mobile-parameter: mobile
watchdog.authentication.sms-code-login.verification.token-parameter: verification-token
watchdog.authentication.sms-code-login.processing-url: /authenticate/sms_code
watchdog.authentication.sms-code-login.default-target-url: /
watchdog.authentication.sms-code-login.failure-url: /login?error&approach=sms_code-login