spring:
  profiles:
    active: dev

---
spring.profiles: dev

server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:user-center;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

  redis:
    host: 192.168.199.201
    port: 6379
    password: 123456
    timeout: PT5S
  data.redis.repositories.enabled: false

  thymeleaf.cache: false



---
#spring.profiles: prod
#
#server:
#  port: 80
#  error.whitelabel.enabled: false
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.199.205:3306/user-center?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
#    username: le
#    password: 123456
#  data.redis.repositories.enabled: false

